# Generated by Django 3.2 on 2022-10-15 06:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('live', 'Live'), ('full_time', 'Full Time'), ('delayed', 'Delayed')], db_index=True, default='confirmed', max_length=15)),
                ('home_score', models.IntegerField(default=-1)),
                ('away_score', models.IntegerField(default=-1)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=6)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away', to='teams.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tournaments.tournament')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
